
| 07-01 16:45:03 [0.0, 0.015625, 0.03125, 0.046875, 0.0625, 0.078125, 0.09375, 0.109375, 0.125, 0.140625, 0.15625, 0.171875, 0.1875, 0.203125, 0.21875, 0.234375, 0.25, 0.265625, 0.28125, 0.296875, 0.3125, 0.328125, 0.34375, 0.359375, 0.375, 0.390625, 0.40625, 0.421875, 0.4375, 0.453125, 0.46875, 0.484375, 0.5], 0.0
| 07-01 16:45:05 epoch: 000| time: 2.1s| train loss: +1.213e+01 | test loss: +nan |
| 07-01 16:45:05 epoch: 000| train loss i: nan test loss i: nan |
/itet-stor/khaefeli/net_scratch/conda_envs/SPECTRE/lib/python3.9/site-packages/torch/optim/lr_scheduler.py:154: UserWarning: The epoch parameter in `scheduler.step()` was not necessary and is being deprecated where possible. Please use `scheduler.step()` to step the scheduler. During the deprecation, if epoch is different from None, the closed form is used instead of the new chainable form, where available. Please open an issue if you are unable to replicate your use case: https://github.com/pytorch/pytorch/issues/new/choose.
  warnings.warn(EPOCH_DEPRECATION_WARNING, UserWarning)
/itet-stor/khaefeli/net_scratch/conda_envs/SPECTRE/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/itet-stor/khaefeli/net_scratch/conda_envs/SPECTRE/lib/python3.9/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/usr/itetnas04/data-scratch-01/khaefeli/data/discrete_ddpm_graphs/edp_simple.py", line 202, in fit
    wandb_dict.update({f"degree_mmd_{num_noiselevel}": lastmmd[num_noiselevel]["degree"],f"cluster_mmd_{num_noiselevel}": lastmmd[num_noiselevel]["cluster"],f"orbit_mmd_{num_noiselevel}": lastmmd[num_noiselevel]["orbit"],f"likelyhood_{num_noiselevel}": lastmmd[num_noiselevel]["likelyhood"],"trainloss": mean_train_loss,"testloss": mean_test_loss})
KeyError: 32
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/itetnas04/data-scratch-01/khaefeli/data/discrete_ddpm_graphs/edp_simple.py", line 294, in <module>
    train_main(config_dict, args)
  File "/usr/itetnas04/data-scratch-01/khaefeli/data/discrete_ddpm_graphs/edp_simple.py", line 275, in train_main
    fit(model, optimizer, None, train_dl,
  File "/usr/itetnas04/data-scratch-01/khaefeli/data/discrete_ddpm_graphs/edp_simple.py", line 205, in fit
    wandb_dict.update({f"degree_mmd_{num_noiselevel}": lastmmd[num_noiselevel]["degree"],f"cluster_mmd_{num_noiselevel}": lastmmd[num_noiselevel]["cluster"],f"orbit_mmd_{num_noiselevel}": lastmmd[num_noiselevel]["orbit"],"trainloss": mean_train_loss,"testloss": mean_test_loss})
KeyError: 32